name: Java Maven Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      PORT: 8088
      DOCKER_IMAGE: milankovac99/praksa2022-image:latest
      KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          
  
      - name: Start Docker container locally
        run: |
           docker run -d -e PORT=8088 -p 8088:8088 milankovac99/praksa2022-image:latest


      - name: Download and install Minikube
        run: |
         curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
         sudo install minikube /usr/local/bin/

      - name: Start Minikube
        run: minikube start --driver=docker --wait=false
        
      - name: Set KUBECONFIG
        run: echo "$(minikube -p minikube kubeconfig)" > $HOME/.kube/config

      - name: Update Deployment image
        run: kubectl set image deployment/praksa2022-deployment praksa2022-image=milankovac99/praksa2022-image:latest

      - name: Check rollout status
        run: kubectl rollout status deployment/praksa2022-deployment



           

