name: Java Maven Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      PORT: 8088
      DOCKER_IMAGE: milankovac99/praksa2022-image:latest
      KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     - name: Set KUBECONFIG
        run: export KUBECONFIG=/home/.kube/kubeconfig

        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Update Deployment image
        run: kubectl set image deployment/praksa2022-deployment praksa2022-image=$DOCKER_IMAGE

      - name: Check rollout status
        run: kubectl rollout status deployment/praksa2022-deployment



           

